#!/bin/bash

command=$1

if [[ -z $command ]]; then
    echo usage
fi

function build() {
    cmake -B build -S .
    make -C build
}

[[ $command == "build" ]] && build

[[ $command == "compile_commands" ]] && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .

if [[ $command == "run" ]]; then
    build
    ./build/TODO_ChangeProjectName
fi
