#!/bin/bash

command=$1

build_dir=build

if [[ -z $command ]]; then
    echo usage
fi

function build() {
    cmake -B $build_dir -S .
    make -C $build_dir
}

[[ $command == "build" ]] && build

[[ $command == "compile_commands" ]] && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .

[[ $command == "test" ]] && make test -C $build_dir

if [[ $command == "run" ]]; then
    build
    ./$build_dir/TODO_ChangeProjectName
fi
